### ISSUE TITLE
external storage access

### ISSUE THREAD

**Issue by WantedLad** [longjunyu2/winlator#110]
Winlator 7.1.2 GlibC
Device info:
Sony Xperia XZ2 Compact
Snapdragon 845 Android 10
i can't get write access to external storage, whenever i add external storage from container the target path remain blank so i need to write manually the external drive target path, is there another way to let winlator have full access to external storage

![Screenshot_20240910-141625](https://github.com/user-attachments/assets/aa9ff24e-0ec9-41b9-a5ad-c205b0c58b47)
![Screenshot_20240910-141618](https://github.com/user-attachments/assets/763894d5-fe99-4c32-bcea-08c18c444dc8)

**Comment by WantedLad** [comment]
maybe android permission issue idk. I've tried the 7.13 GlibC and it is now crashing whenever i allow external storage access, i can't unlock my bootloader so custom rom or installing to sdcard isn't an option for me (but did enabled force allow apps on external sdcard option and it doesnt' work..)
Also i tried to add androidRequestExternalStorageLegacy="true" to androidmanifest.xml to no luck, i can't program LoL. But i looked for some pages about android 10 and found that line of manifest should be added

**Comment by longjunyu2** [comment]
@WantedLad This issue was resolved in version 7.1.3. (There is a minor bug where adding a USB drive allows the file manager to map the root directory of the USB drive, which can cause a crash. However, mapping any subdirectory of the USB drive works fine.) In reality, we do not actually need full file access permissions; what we need is the accessible folders provided by the file manager.

**Comment by longjunyu2** [comment]
> maybe android permission issue idk. I've tried the 7.13 GlibC and it is now crashing whenever i allow external storage access, i can't unlock my bootloader so custom rom or installing to sdcard isn't an option for me (but did enabled force allow apps on external sdcard option and it doesnt' work..) Also i tried to add androidRequestExternalStorageLegacy="true" to androidmanifest.xml to no luck, i can't program LoL. But i looked for some pages about android 10 and found that line of manifest should be added

Try selecting a folder on the external storage device instead of the entire external storage. This bug will be fixed in the future.

**Comment by WantedLad** [comment]
thank you, i have just tried to add external storage subdirectory and it works/no crash but after opening the container i still can't get write access to it. i'm gonna stick to internal storage for now :)

**Comment by longjunyu2** [comment]
I have tested on Android 12 and Android 14, and it is able to write sdcard and USB storage device.

please check if your SD card is writable in the Android file manager.

**Comment by WantedLad** [comment]
sdcard is writable on built in file manager and on installed third party file manager, like Zarchiver, MT manager

**Comment by magbulogtong81** [comment]
actually, you can just add `/storage/sdcard1` on drives, to add access to external sdcard.

`/storage/sdcard` is a symlink to /storage/{EXT_SDCARD_UUID}, and AFAIK this is true since android kitkat (android 4.4)
![Screenshot_20240914-051715~2](https://github.com/user-attachments/assets/0db436c9-6f24-4ef0-a37b-7957dee31d74)
